### ISSUE TITLE
Integrate this into ActiveDecorator

### ISSUE THREAD

**Issue by lunks** [a2ikm/jbuilder-active_decorator#1]
We should port this code into it. Shouldn't be too hard with some `defined?(Jbuilder)` guards.

**Comment by a2ikm** [comment]
I made a pull-request, https://github.com/amatsuda/active_decorator/pull/29.
Could you see that? Thanks.

**Comment by lunks** [comment]
Build is currently failing, care to investigate?

**Comment by a2ikm** [comment]
Thank you for checking.
Sorry, I forgot to add jbuilder to gemfiles for tests, and fixed it.
But still failing for ruby 1.8.7 which jbuilder doesn't support.

**Comment by lunks** [comment]
Hmm I guess there should be a way to disable this for 1.8.7 for this to
ever be pushed in.

**Comment by a2ikm** [comment]
You mean like putting `require "jbuilder" if RUBY_VERSION >= "1.9"` to tests?
It seems tricky for me.

For now, I think it is a way to wait for ActiveDecorator's dropping 1.8.7 support. It's end-of-lie is this June.

**Comment by a2ikm** [comment]
https://github.com/amatsuda/active_decorator/pull/29 is merged, so ActiveDecorator doesn't decorate Jbulder objects since v0.4.0 :angel:
